django-projects/TourismApp/TourismApp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('venues/', include('venues.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

django-projects/TourismApp/venues/urls.py
from django.urls import path, re_path

from . import views


app_name = 'venues'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('show-results/', views.Mapview.as_view(), name='mapview'),
    re_path('get_location_string/$', views.ReverseGeocode.as_view(), name='reverse-geocode'),
    re_path('filter-results/$', views.Filter.as_view(), name='filter'),
    re_path('get_comments/$', views.GetComments.as_view(), name='getcomments'),
    re_path('get_images/$', views.GetImages.as_view(), name='getimages'),
    re_path('get_avgrating/$', views.GetAvgRating.as_view(), name='getavgrating'),
    re_path('new_comment/$', views.NewComment.as_view(), name='newcomment'),
    re_path('remove_comment/$', views.RemoveComment.as_view(), name='removecomment'),
    re_path('new_image/$', views.NewImage.as_view(), name='newimage'),
    re_path('remove_image/$', views.RemoveImage.as_view(), name='removeimage'),
    path('show-results/<str:place_id>/', views.Detail.as_view(), name='detail'),
    path('show-results/<str:place_id>/<str:content_page>', views.Detail.as_view(), name='detail'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('delete-account/', views.DeleteAccount.as_view(), name='del_account'),
    path('change-password/', views.PasswordChange.as_view(), name='my-account')
]

django-projects/TourismApp/venues/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe

class SignupForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label=mark_safe("<strong>Nombre de usuario</strong>"))
    email = forms.EmailField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}), label=mark_safe("<strong>Correo electrónico</strong>"))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label=mark_safe("<strong>Introduce una contaseña</strong>"))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label=mark_safe("<strong>Repite tu contraseña</strong>"))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class AccModForm(UserCreationForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label=mark_safe("<strong>Introduce la contraseña actual</strong>"))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label=mark_safe("<strong>Introduce la nueva contaseña</strong>"))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label=mark_safe("<strong>Repite la nueva contraseña</strong>"))

    class Meta:
        model = User
        fields = ('old_password','password1', 'password2')
        

class ImageUploadForm(forms.Form):
    caption = forms.CharField(max_length=250)
    image = forms.ImageField()

django-projects/TourismApp/venues/views.py
import requests
import json
import geocoder
import base64
import bleach
import pandas as pd
from math import sin, cos, sqrt, atan2, radians
from dateutil import parser
from django.core.files.base import ContentFile
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.utils.html import escape
from django.contrib import messages
from django.contrib.auth.hashers import make_password
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.urls import reverse_lazy
from django.views import generic, View
from .forms import SignupForm, ImageUploadForm, AccModForm
from requests.auth import HTTPBasicAuth
from .categories import *
from .webservice_endpoints import *
from .variables import R, request_radius, days_es

#------------------------------------------------------------------------------------#
# Vista de eliminación de usuario.                                                   #
#                                                                                    #
# Gestiona el borrado de usuarios en la BD del servicio web                          #
#------------------------------------------------------------------------------------#

class DeleteAccount(View):
    template_name_on_success = 'venues/index-desktop.html'
    template_name_on_success_mobile = 'venues/index-mobile.html'
    template_name_on_error = 'venues/error-template.html'

    def get(self, request):
        print("deleting...")
        url = "http://127.0.0.1:8000/users/my_account/"
        response = requests.delete(url, headers = {'Authorization':'token '+request.session['auth_token']})

        if response.ok:
            context={}
            if request.user_agent.is_mobile:
                return render(request, self.template_on_success_mobile, context)
            else:
                return render(request, self.template_on_success, context)
        else:
            return render(request, self.template_name_on_error, {"No se ha podido eliminar la cuenta. Por favor, inténtalo más tarde."})

#------------------------------------------------------------------------------------#
# Vista de alta de usuario.                                                          #
#                                                                                    #
# Gestiona el renderizado de la página de sing-up y la creación de nuevos usuarios   #
# en la BD del servicio web                                                          #
#------------------------------------------------------------------------------------#

class SignUp(View):
    form_class = SignupForm
    template_name_on_success = 'venues/index-desktop.html'
    template_name_on_success_mobile = 'venues/index-mobile.html'
    template_name_on_login_error = 'registration/login.html'
    template_name_on_signup_error = 'registration/signup.html'
    template_name = 'registration/signup.html'

    def get(self, request):
        request.session['signup_from'] = request.META.get('HTTP_REFERER', '/')
        return render(request, self.template_name, {'form':self.form_class})
    

    def post(self, request):
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = bleach.clean(form.cleaned_data.get('username'))
            raw_password = bleach.clean(form.cleaned_data.get('password1'))
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            data = {'username':username,'password':raw_password}
            response = requests.post(signup_endpoint, data)
            
            if response.ok:
                response = requests.post(login_endpoint, data = {'username':username,'password':raw_password})
                if response.ok:
                    token = response.json()['token']
                    request.session['auth_token'] = token
                    context = {}
                    if request.user_agent.is_mobile:
                        return render(request, self.template_name_on_success_mobile, context)
                    else:
                        return render(request, self.template_name_on_success, context)
                else:
                    messages.error(request,'El usuario no existe.')
                    context = {'form':AuthenticationForm}
                    return render(request, self.template_name_on_login_error, context)
            else:
                messages.error(request,'Algo salió mal al intentar crear tu cuenta. Inténtalo más tarde.')
                context = {'form':self.form_class}
                return render(request, self.template_name_on_signup_error, context)
        else:
            return render(request, self.template_name_on_signup_error, {'form':form})
                
           
#------------------------------------------------------------------------------------#
# Vista de cambio de contraseña.                                                     #
#                                                                                    #
# Gestiona el renderizado de la página de usuario y la modificación de las creden-   #
# ciales de los usuarios en la BD del servicio web                                   #
#------------------------------------------------------------------------------------#

class PasswordChange(View):
    template_name = 'registration/password_change.html'
    template_name_on_success = 'venues/index-desktop.html'
    template_name_on_success_mobile = 'venues/index-mobile.html'
    template_name_on_error = 'venues/error-template.html'
    form_class = AccModForm

    def get(self, request):
        return render(request, self.template_name, {'form':self.form_class})

    def post(self, request):
        url = "http://127.0.0.1:8000/users/my_account/"
        form = AccModForm(request.POST)
        if form.is_valid():
            user = User.objects.get(username=self.request.user)
            if user.check_password(request.POST['old_password']):
                response = requests.put(url, data={'password':bleach.clean(request.POST['password2'])}, headers = {'Authorization':'token '+request.session['auth_token']})
                if response.ok:
                    data = {'password':bleach.clean(request.POST['password2'])}
                    user.set_password(bleach.clean(request.POST['password1']))
                    user.save()
                    if request.user_agent.is_mobile:
                        return render(request, self.template_name_on_success_mobile, {})
                    else:
                        return render(request, self.template_name_on_success, {})
                else:
                    return render(request, self.template_name_on_error, {'error':"Ha habido un problema al intentar modificar la información de inicio de sesión. Por favor, inténtalo más tarde"})
            else:
                messages.error(request, "La contraseña actual introducida no es correcta")
                return render(request, self.template_name, {'form':self.form_class})
        else:
            return render(request, self.template_name, {'form':form})
            
#------------------------------------------------------------------------------------#
# Vista de inicio de sesión.                                                         #
#                                                                                    #
# Gestiona el renderizado de la página de log-in y la validación de las credencia-   #
# les de los usuarios contra el servicio web                                         #
#------------------------------------------------------------------------------------#

class Login(View):
    form_class = AuthenticationForm
    template_name_on_success = 'venues/index-desktop.html'
    template_name_on_success_mobile = 'venues/index-mobile.html'
    template_name_on_error = 'registration/login.html'
    template_name = 'registration/login.html'

    def get(self, request):
        print(request.META.get('HTTP_REFERER', '/'))
        request.session['login_from'] = request.META.get('HTTP_REFERER', '/')
        return render(request, self.template_name, {'form':self.form_class})
    
    def post(self, request):
        username = bleach.clean(self.request.POST['username'])
        password = bleach.clean(self.request.POST['password'])
        if request.session['login_from']:
                    print("you logged from: "+request.session['login_from'])
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = requests.post(login_endpoint, data={'username':username, 'password':password})
            if response.ok:
                token = response.json()['token']
                request.session['auth_token'] = token
                context = {}
                if request.session['login_from']:
                    return HttpResponseRedirect(request.session['login_from'])
                else:
                    if request.user_agent.is_mobile:
                        return render(request, self.mobile_template_on_success_mobile, context)
                    else:
                        return render(request, self.template_name_on_success, context)
            else:
                messages.error(request,'Algo salió mal al intentar iniciar tu sesión. Inténtalo más tarde.')
                context = {'form':self.form_class}
                return render(request, self.template_name_on_error, context)
        else:
            messages.error(request,'Usuario o contraseña incorrectos')
            context = {'form':self.form_class}
            return render(request, self.template_name_on_error, context)
        


#------------------------------------------------------------------------------------#

django-projects/TourismApp/venues/templates/venues/index-desktop.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- PAGE settings -->
  <link rel="icon" href="{% static 'venues/backgrounds/applogo.png' %}">
  <title>TourismApp - Home</title>
  <meta name="description" content="Wireframe design of a cover page by Pingendo">
  <meta name="keywords" content="Pingendo bootstrap example template wireframe cover">
  <meta name="author" content="Pingendo">
  <!-- CSS dependencies -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" type="text/css" href="{% static 'venues/wireframe-index.css' %}">
</head>
<style>
::-webkit-scrollbar {
    width: 6px;
    background-color: #F5F5F5;
} 

::-webkit-scrollbar-thumb {
    background-color: #555555;
}

::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
    background-color: #555555;
}

</style>
<body class="text-center bg-dark">
  <div class="p-3 h-100 d-flex flex-column">
    <div class="container mb-auto">
      <div class="row">
        <div class="mx-auto col-md-9">
          <nav class="navbar navbar-expand-md navbar-dark">
            <div class="container">
              <a class="navbar-brand" href="#"><b>TourismApp</b></a>
              <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent" aria-controls="navbar2SupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span> </button>
              <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active" href="#"><b>Inicio</b></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#"><b>Contacto</b></a>
                  </li> {% if request.user.is_authenticated %} 
                  <li class="nav-item">
                    <a id="logout" class="nav-link" href="{% url 'logout' %}"><strong>Cerrar sesión</strong></a>
                  </li>
                  <li class="nav-item">
                    <p><a class="nav-link" href="{% url 'venues:my-account' %}"><strong>Mi cuenta</strong></a></p>
                  <li>
                   {% else %} <li class="nav-item">
                    <a class="nav-link" href="{% url 'venues:login' %}"><strong>Iniciar sesión</strong></a>
                  </li> {% endif %}
                </ul>
              </div>
            </div>
          </nav>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row mb-5 pb-0">
        <div class="col-md-8 mx-auto">
          <h1 class="cover-heading mt-5"><b>Encuentra lo que buscas cerca de ti</b></h1>
          <p class="lead mb-5">Esta app te permite encontrar puntos de interés de una determinada categoría presentes en el área circundante. Obtén la ruta más eficiente hacia los destinos seleccionados, visualiza fotos y valoraciones de otros usuarios o aporta las tuyas.</p>
          <label for="category"><strong>Introduce una dirección</strong></label>
            <div class="" id="autoCompleteDiv">
              <input class="form-control d-block w-100"  id="pac-input" type="text" placeholder="Enter a location">
            </div>
            <BR>
            <a href="#!" onclick="getLocation()"><strong style="color:white;">Usar mi ubicación</strong></a>
          <form class="needs-validation" novalidate="" action="{% url 'venues:mapview' %}" method="post">
          {% csrf_token %}
            <BR>
            <div class="row ml-5 pl-5">
              <BR>
              <div class="col-md-5 mb-3 ml-5 pl-5"> <label for="category"><strong>¿Qué estás buscando?</strong></label> <select class="custom-select d-block w-100" id="category" name="category" required="">
                  <optgroup label="Comida">
                  <option value="restaurant">Restaurantes</option>
                  <option value="meal_takeaway">Comida para llevar</option>
                  <option value="food">Todos</option>
                  </optgroup>
                  <optgroup label="Ocio">
                  <option value="amusement_park">Parque de atracciones</option>
                  <option value="bowling_alley">Bolera</option>
                  <option value="casino">Casino</option>
                  <option value="movie_theater">Cine</option>
                  <option value="spa">Spa / Centro de belleza</option>
                  <option value="stadium">Estadio</option>
                  <option value="zoo">Zoo</option>
                  <option value="leisure">Todos</option>
                  </optgroup>
                  <optgroup label="Cultura">
                  <option value="art_gallery">Galería de arte</option>
                  <option value="library">Biblioteca</option>
                  <option value="museum">Museo</option>
                  <option value="religious_emplacements">Templos religiosos</option>
                  <option value="park">Parques</option>
                  <option value="monument">Monumentos</option>
                  <option value="culture">Todos</option>
                  </optgroup>
                  <optgroup label="Servicios">
                  <option value="lodging">Alojamiento</option>
                  <option value="car_rental">Alquiler de vehículos</option>
                  <option value="parking">Parking</option>
                  <option value="atm">Cajero</option>
                  <option value="campground">Cámping</option>
                  <option value="rv_park">Parque de caravanas</option>
                  <option value="gas_station">Gasolinera</option>
                  <option value="police">Policía</option>
                  <option value="services">Todos</option>
                  </optgroup>
                  <optgroup label="Tiendas">
                  <option value="book_store">Librería</option>
                  <option value="clothing_store">Ropa</option>
                  <option value="convenience_store">Supermercado / Hipermercado</option>
                  <option value="hardware_store">Electrónica</option>
                  <option value="shopping_mall">Centro comercial</option>
                  <option value="other_stores">Otros</option>
                  <option value="shopping">Todos</option>
                  </optgroup>
                  <optgroup label="Servicios sanitarios">
                  <option value="hospital">Hospitales y Centros Médicos</option>
                  <option value="pharmacy">Farmacias</option>
                  <option value="medical_services">Todos</option>
                  </optgroup>
                  <optgroup label="Bares y clubs">
                  <option value="bar">Bar</option>
                  <option value="night_club">Club/Pub</option>
                  <option value="bar_and_clubs">Todos</option>
                  </optgroup>
                  <optgroup label="Transporte">
                  <option value="taxi_stand">Parada de taxis</option>
                  <option value="airport">Aeropuerto</option>
                  <option value="bus_station">Estación / parada de bus</option>
                  <option value="train_station">Estación / parada de tren</option>
                  <option value="subway_station">Estación / parada de metro</option>
                  <option value="transport">Todos</option>
                  </optgroup>
                </select>
                <BR>
                <div class="invalid-feedback"> Please select a valid category. </div>
                <div><input id="position" type="hidden" name="position"/></div>
                <div><input id="gps" type="hidden" name="gps" value=true /></div>
                <button class="btn btn-primary btn-lg btn-block mt-3" type="submit"><strong>Buscar</strong></button>
              </div>
            </div>
          </form>
        </div>
      </div>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </div>
  </div>
</body>
<script src="{% static 'venues/jquery-3.3.1.min.js' %}" async defer></script>
<script>
    var x = document.getElementById("position");

    var options = {
      enableHighAccuracy: true,
      timeout: 5000,
      maximumAge: 0
    };

    function error(error) {
      switch(error.code) {
        case error.POSITION_UNAVAILABLE:
          alert("No ha sido posible obtener la información de ubicación. Por favor, inténtalo más tarde")
          break;
        case error.TIMEOUT:
          alert("Se ha excedido el tiempo de espera para obtener la información de ubicación.")
          break;
        case error.UNKNOWN_ERROR:
          alert("No ha sido posible obtener la información de ubicación. Por favor, inténtalo más tarde")
          break;
      }
    };

    function getLocation() {
        document.getElementById('gps').value = true;
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(setPositionValue, error, options);
        } else {
            alert("Geolocation is not supported by this browser.");
        }
    }

    function setPositionValue(position) {
        x.value = position.coords.latitude + "," + position.coords.longitude; 
        getLocationString();
    }

    function initAutoComplete(){
        var input = document.getElementById('pac-input');
        autocomplete = new google.maps.places.Autocomplete(input);
        autocomplete.setFields(
            ['address_components', 'geometry', 'icon', 'name']);

        autocomplete.addListener('place_changed', function() {
          var place = autocomplete.getPlace();

          if (!place.geometry) {
            window.alert("No details available for input: '" + place.name + "'");
            getLocation();
            return;
          }

          if (place.geometry.viewport) {
            x.value = place.geometry.location.lat()+","+place.geometry.location.lng();
            document.getElementById('gps').value=false;
          }
        });

    }

    function getLocationString(){
            document.getElementById("pac-input").value = "Obteniendo dirección..."
            $.ajax({
                url : "{% url 'venues:reverse-geocode' %}"+"?LatLng="+x.value,
                dataType: "json",  
                method : "GET",
                success : function (data) {
                    document.getElementById("pac-input").value = data['results'][0]['formatted_address'];
                },
                error : function (data){
                    alert("Ha habido un error, inténtalo más tarde.");
                }
            });
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDEDOKsldYBl9NQ6Ml9uYVGOW2vosygeSs&libraries=places&callback=initAutoComplete"
        async defer></script>

</html>

django-projects/TourismApp/venues/templates/venues/index-global (copia).html
<!DOCTYPE html>
<html>
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- PAGE settings -->
  <link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
  <title>Cover</title>
  <meta name="description" content="Wireframe design of a cover page by Pingendo">
  <meta name="keywords" content="Pingendo bootstrap example template wireframe cover">
  <meta name="author" content="Pingendo">
  <!-- CSS dependencies -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" type="text/css" href="{% static 'venues/index-global.css' %}">
</head>

<body class="text-center bg-dark">
  <div class="p-3 h-100 d-flex flex-column">
    <div class="container mb-auto">
      <div class="row">
        <div class="mx-auto col-md-9">
          <nav class="navbar navbar-expand-md navbar-dark">
            <div class="container">
              <a class="navbar-brand" href="#"><b>TourismApp</b></a>
              <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent" aria-controls="navbar2SupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span> </button>
              <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link active" href="#"><b>Home</b></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#"><b>Features</b></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#"><b>Contact</b></a>
                  </li>
                  {% if request.user.is_authenticated %} 
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'logout' %}">Log out</a>
                    </li> 
                 {% else %} 
                   <li class="nav-item">
                     <a class="nav-link" href="{% url 'venues:login' %}">Log in</a>
                   </li> 
                 {% endif %}
                </ul>
              </div>
            </div>
          </nav>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto">
          <h1 class="cover-heading"><b>Encuentra puntos de interés cercanos!</b></h1>
          <p class="lead">Esta app te permite encontrar puntos de interés de una determinada categoría ordenados por relevancia. Obtén la ruta más eficiente hasta tus destinos seleccionados, visualiza fotos y valoraciones de otros usuarios y deja los tuyos!</p>
          <form class="needs-validation" novalidate="" action="{% url 'venues:mapview' %}" method="post">
          {% csrf_token %}
            <div class="col-md-12 w-100 px-5 mb-3 mt-3"> <select class="custom-select d-block w-100" id="state" required="">
                <option value="">Escoge una categoría...</option>
                <option value="food">Comida</option>
                <option value="leisure">Ocio</option>
                <option value="culture">Cultura</option>
                <option value="services">Servicios</option>
                <option value="shopping">Tiendas</option>
                <option value="medical_services">Servicios sanitarios</option>
                <option value="bar_and_clubs">Bares y clubs</option>
                <option value="transport">Transporte</option>
                <option value="other">Otros</option>
              </select>
              <div class="invalid-feedback"> Please provide a valid state. </div>
              <div><input id="position" type="hidden" name="position"/></div>
              <div><input id="radius" type="hidden" name="radius" value="1500"/></div>
              <button class="btn btn-primary btn-lg btn-block mt-3" type="submit">Buscar</button>
        </div>
      </div>
    </div>
    <div class="container mt-auto">
      <div class="row">
        <div class="col-md-12">
          <p class="mt-auto text-secondary">Cover template for <a href="#" class="text-white">Bootstrap</a>, by <a href="#" class="text-white">@mdo</a>.</p>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <pingendo onclick="window.open('https://pingendo.com/', '_blank')" style="cursor:pointer;position: fixed;bottom: 20px;right:20px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:220px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white">Made with Pingendo Free&nbsp;&nbsp;<img src="https://pingendo.com/site-assets/Pingendo_logo_big.png" class="d-block" alt="Pingendo logo" height="16"></pingendo>
</body>
<script>
    var x = document.getElementById("position");
    function getLocation() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(setPositionValue);
        } else {
            alert("Geolocation is not supported by this browser.");
        }
    }

    function setPositionValue(position) {
        x.value = position.coords.latitude + "," + position.coords.longitude; 
    }
    window.addEventListener('load', getLocation);
</script>

</html>